#!/bin/sh
# Host tests for the runtime: the copy of stdout/stderr into its log, Horizon
# file access (rights, descriptor modes, open-file path matching) and the
# analog-stick mouse cursor.
set -eu
root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
build="$(mktemp -d "${TMPDIR:-/tmp}/wine-nx-console.XXXXXX")"
trap 'rm -rf "$build"' EXIT HUP INT TERM
flags="-std=gnu11 -Wall -Wextra -Werror -fsanitize=address,undefined -fno-omit-frame-pointer"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/std_stream_lines.c" -o "$build/std_stream_lines"
"$build/std_stream_lines"
"${CC:-clang}" $flags -I"$root/include" "$root/wine-nx-probe/tests/horizon_file_access.c" -o "$build/file_access"
"$build/file_access"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/pointer_cursor.c" -o "$build/pointer_cursor"
"$build/pointer_cursor"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_message_queue.c" -o "$build/message_queue"
"$build/message_queue"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_win_timers.c" -o "$build/win_timers"
"$build/win_timers"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_msg_queue.c" -o "$build/msg_queue"
"$build/msg_queue"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_clipboard.c" -o "$build/clipboard"
"$build/clipboard"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/launcher_list.c" -o "$build/launcher_list"
"$build/launcher_list"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/sd_read_cache.c" -o "$build/sd_read_cache"
"$build/sd_read_cache"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_registry.c" -o "$build/registry"
"$build/registry"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_read_redirect.c" -o "$build/read_redirect"
"$build/read_redirect"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_object_dirs.c" -o "$build/object_dirs"
"$build/object_dirs"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_keyboard.c" -o "$build/keyboard"
"$build/keyboard"
"${CC:-clang}" $flags "$root/wine-nx-probe/tests/horizon_free_range.c" -o "$build/free_range"
"$build/free_range"
"${CC:-clang}" $flags -I"$root/include" "$root/wine-nx-probe/tests/xinput_nx_pad.c" -o "$build/xinput_pad"
"$build/xinput_pad"
python3 "$root/wine-nx-probe/tools/make-7zr-tree.py" "$build/drive_c" >/dev/null
