@ stdcall BTCpuFlushInstructionCache2(ptr long)
@ stdcall BTCpuFlushInstructionCacheHeavy(ptr long)
@ stdcall BTCpuGetBopCode()
@ stdcall BTCpuGetContext(long long ptr ptr)
@ stdcall BTCpuIsProcessorFeaturePresent(long)
@ stdcall BTCpuNotifyMemoryFree(ptr long long long long)
@ stdcall BTCpuNotifyMemoryProtect(ptr long long long long)
@ stdcall BTCpuNotifyUnmapViewOfSection(ptr long long)
@ stdcall BTCpuProcessInit()
@ stdcall BTCpuThreadInit()
@ stdcall BTCpuResetToConsistentState(ptr)
@ stdcall BTCpuSetContext(long long ptr ptr)
@ stdcall BTCpuSuspendLocalThread(long ptr)
@ stdcall -norelay BTCpuSimulate()
@ stdcall BTCpuTurboThunkControl(long)
@ stdcall BTCpuUpdateProcessorInformation(ptr)
@ stdcall __wine_get_unix_opcode()
